// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgT6xrlwvVb7DImq5XnLckNXeoKGEltss',
    appId: '1:24442748632:web:2a85256b961fb63c9861ad',
    messagingSenderId: '24442748632',
    projectId: 'crud123-5fa75',
    authDomain: 'crud123-5fa75.firebaseapp.com',
    storageBucket: 'crud123-5fa75.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWOHKamDYE3GLr1rPQ0B8g_B_LEnNIcxI',
    appId: '1:24442748632:android:0f29cd0668c092969861ad',
    messagingSenderId: '24442748632',
    projectId: 'crud123-5fa75',
    storageBucket: 'crud123-5fa75.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ9RsqlC5MAZtk14h16Zz_kYgX8OinFWc',
    appId: '1:20067809417:web:937d51531ac2ff32236e58',
    messagingSenderId: '20067809417',
    projectId: 'crud-43bc9',
    authDomain: 'crud-43bc9.firebaseapp.com',
    storageBucket: 'crud-43bc9.firebasestorage.app',
  );

}